### ISSUE TITLE
Local error handlers

### ISSUE THREAD

**Issue by m1raynee** [EQUENOS/dislash.py#22]
Local error handlers will have to work the same way as in discord.py 
Minimal syntax:
```py
@slash_commands.command(...)
async def random_command(...):
    # random stuff

@random_command.slash_error
async def some_eh(inter, error):
    # eh stuff 
```
~~how to add the labels aaa idk I'm lost~~

**Comment by EQUENOS** [comment]
Added this feature in v1.1.0, thanks for the suggestion.
