### ISSUE TITLE
Allow for decorator chaining when a decorator modifies the kwargs

### ISSUE THREAD

**Issue by dob9601** [EQUENOS/dislash.py#29]
I've got a decorator that adds an additional kwarg to a function and have been using this with the default discord.py framework. This decorator helps integrate django with discord.py by using the user id in the context to fetch the user object from the django database. However, due to the code shown here:
https://github.com/EQUENOS/dislash.py/blob/6aa5f28c6c43799d9af089a2b98cf61affb978f7/dislash/slash_commands/slash_core.py#L365-L374
That kwarg never actually reaches the function.
Would it be possible to add support for additional custom kwargs by exposing all additional kwargs to the command function?

**Comment by EQUENOS** [comment]
I'll add custom kwargs support in the nearest patch, thank you for sharing this issue

**Comment by EQUENOS** [comment]
Additional custom kwargs are now supported in dislash.py v1.2.3
