### ISSUE TITLE
Disable auto-registration of slash commands

### ISSUE THREAD

**Issue by celunah** [EQUENOS/dislash.py#33]
How do I disable the automatic registration of slash commands?
My bot seems to have ratelimited itself with auto-registration.

**Comment by EQUENOS** [comment]
The library makes 1 API request to automatically update all global commands and 1 API request for each guild with local commands. Your bot won't be ratelimited unless you register a command in a ton of guilds.
If you're registering the commands in all guilds where your bot is active, consider global registration instead.

**Comment by celunah** [comment]
also one more thing:
when i updated the library i got a `This interaction failed` message and then the slash commands disappeared and never registered again. What happened?

**Comment by EQUENOS** [comment]
If there're no commands in your code, the library unregisters all existing commands.
In other words, the lib keeps the registered slash commands in sync with your code

**Comment by celunah** [comment]
The commands in my cog remained the same but the bot does not seem to register them and I can assure you that an hour has elapsed already.

**Comment by celunah** [comment]
ok, it finally did register, ig that is it for the issue
