### ISSUE TITLE
Add Select Menu Disabling 

### ISSUE THREAD

**Issue by WhoIsConch** [EQUENOS/dislash.py#34]
I noticed that the [official Discord API select menu docs](https://discord.com/developers/docs/interactions/message-components#select-menus) have the option for disabling the menus, yet this isn't an option in Dislash.py. I'd appreciate it if it was a thing, it'd make some stuff so much easier, such as timeouts or after selection.

![image](https://user-images.githubusercontent.com/69608854/125364933-6150d980-e341-11eb-899f-cbf3a82c408c.png)

**Comment by EQUENOS** [comment]
Seems like they added this field later
Thanks for sharing this, I'll add this asap
