### ISSUE TITLE
"don't nest sub_command_groups and sub_commands to the same parent"

### ISSUE THREAD

**Issue by Xenos6666** [EQUENOS/dislash.py#37]
The discord API seems to allow this just fine, this limitation should be removed from the package.

**Comment by EQUENOS** [comment]
I suspect that you misunderstood something, have a look at this image from the official documentation:
![image](https://user-images.githubusercontent.com/50338932/128000060-9ebad90e-6150-4b4d-9857-894d6bf2a349.png)

**Comment by Xenos6666** [comment]
I already looked at it, this page doesn't state anything about having subcommands and subcommand-groups on the same levels, none of the example confirm nor deny that it's possible, so I tested it, and it does indeed work perfectly fine

**Comment by Xenos6666** [comment]
Proof: 
![image](https://user-images.githubusercontent.com/78383625/128000613-c0f04efc-9b7c-4198-b516-01b7bcf21f47.png)

**Comment by EQUENOS** [comment]
My bad; I'll fix that as soon as possible

**Comment by Xenos6666** [comment]
Thank you :D

**Comment by EQUENOS** [comment]
Fixed in 1.2.8
