### ISSUE TITLE
Sending a file in a followup's ephemeral Message will throw a 'Cannot Send Empty Message' error

### ISSUE THREAD

**Issue by yagomichalak** [EQUENOS/dislash.py#41]
I tried following up an ephemeral message with a message that contains a file, but it'd say that it cannot send an empty message. When I specified a content, it'd just send the content itself, but not the file.

```py
await interaction.send(type=5, ephemeral=True)
or
await interaction.reply(type=5, ephemeral=True)
or
await interaction.create_response(type=5, ephemeral=True)
```
and at the end
```py

file = discord.File("/path_to_image/image.png")
await interaction.followup(file=file)
```
> discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message

**Comment by EQUENOS** [comment]
Fixed in 1.3.3, thanks for reporting this issue!
