### ISSUE TITLE
Reset Cooldown Doesn't Work

### ISSUE THREAD

**Issue by LextYi** [EQUENOS/dislash.py#44]
I try to use `slash_core.BaseSlashCommand.reset_cooldown(inter)` to reset the cooldown.
But it shows this error: `reset_cooldown() missing 1 required positional argument: 'inter'`

Then I try this: `slash_core.BaseSlashCommand.reset_cooldown(self, inter)`
But it still shows the error: `'SlashCommand' object has no attribute '_buckets'`

**Comment by liemeldert** [comment]
You can't use `slash_core.BaseSlashCommand.reset_cooldown(inter)`, it's not a static method. It's a method of slash command. You need to create an instance of slash command (which can be retrieved using an interaction) and use reset_cooldown on it. 

So, you'd end up with something like this: 
inter.slash_command.reset_cooldown(inter)

This isn't a bug - this is just how python works and as such should be closed.

**Comment by EQUENOS** [comment]
I think we can close this issue after our discussion on the discord server
