### ISSUE TITLE
Interaction bug

### ISSUE THREAD

**Issue by Mysterious-Dev** [EQUENOS/dislash.py#49]
I have this error with slash commands and the same with application commands

![image](https://user-images.githubusercontent.com/40738104/129238672-ce279457-21c6-4d6f-8a4b-2b6de1912277.png)

**Comment by liemeldert** [comment]
Looks like you're replying after the interaction is timed out. What's your code?

**Comment by Mysterious-Dev** [comment]
![image](https://user-images.githubusercontent.com/40738104/129239115-9e4d5dd5-1ea8-416d-944a-4644fdfd55db.png)

**Comment by Mysterious-Dev** [comment]
![image](https://user-images.githubusercontent.com/40738104/129239201-0280e13d-db53-44f1-88b8-5d7e10141191.png)

**Comment by EQUENOS** [comment]
The traceback says that `inter.reply` causes the error. Looks like you're replying to some interactions in a separate event

**Comment by Mysterious-Dev** [comment]
Oh yes, it's on error slash command. Thanks
