### ISSUE TITLE
Use versions for pip packages

### ISSUE THREAD

**Issue by ffuyu** [EQUENOS/dislash.py#50]
As long as you use "latest" without a version, we need to uninstall and reinstall the dislash.py entirely to get the latest features, such as ContextMenus.

**Comment by ffuyu** [comment]
I'm not really sure if it does, pip says it is 1.4.6 but I had to uninstall and reinstall fresh to have the latest features

**Comment by EQUENOS** [comment]
`pip install dislash.py --upgrade` works fine, you don't have to reinstall the library

**Comment by ffuyu** [comment]
what about using `pip install -r requirements.txt`? As far as I see it does not upgrade each time it installs and I have to uninstall dislash.py to get the actual latest

**Comment by m1raynee** [comment]
Add `-U` flag. If you run `pip install -r requirements.txt`, it will install modules it doesn't find. By adding a `-U` flag, it updates all modules from the file. So, it should look something like this: `pip install -U -r requirements.txt`
(P.S.: `-U` is equivalent of `--upgrade`)
